version: '3.9'
services:
  php:
    build: ./www
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html

  db:
    build: ./database
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql-data:
